# Generated by Django 4.1.5 on 2023-01-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phonenum', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField(max_length=10)),
            ],
        ),
    ]
