# Generated by Django 4.0.4 on 2023-01-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LICapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userforms',
            name='phonenum',
            field=models.CharField(max_length=10),
        ),
    ]
